language: node_js
node_js:
  - "10.4.0"
before_install:
  - pwd
  - ls -la
  - sudo apt-get update
  - sudo apt-get install -y python2.7 cmake
  - git clone https://github.com/juj/emsdk.git
  - cd emsdk 
  - ./emsdk install latest
  - ./emsdk activate latest
  - source ./emsdk_env.sh
  - cd ..